# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  back-end-clone-command:
    steps:
      - run: git clone https://github.com/jlmacle/AccessibleTodoList_Backend.git
  back-end-run-command:
    steps:
      - run: cd AccessibleTodoList_Backend && mvn spring-boot:run

executors:
  back-end-executor:
    docker:
      - image: cimg/openjdk:11.0

jobs: 
  back-end-run-job:     
    executor: back-end-executor
    steps: 
      - back-end-run-command   

  back-end-clone-job:
    executor: back-end-executor
    steps:
      - back-end-clone-command

workflows: 
  back-end-run-workflow: 
    jobs:
      - back-end-clone-job
      - back-end-run-job:
        requires:
          - back-end-clone-job
        