#Note: this may lack maturity
version: 2.1

commands:
  back-end-check-config-command:
    steps:
      
      - run: #Configuration check
          echo "Starting the configuration check." 
          && sudo apt install tree && tree src 
          && cd src/main/java/jl/forthem/ 
          && grep "//public static final String CORS_ALLOWED_2" ./Configuration.java 
          && grep "//public static final String CORS_ALLOWED_3" ./Configuration.java 
          && grep "//String\[] origins= {CORS_ALLOWED, CORS_ALLOWED_2" ./Configuration.java

executors:
  back-end-executor:
    docker:
      # primary container
      # https://hub.docker.com/u/circleci/
      - image: circleci/openjdk

jobs:
  back-end-config-check-job:
    executor: back-end-executor
    steps:
      - back-end-check-config-command      

workflows:  
  back-end-config-check-workflow:
    jobs:
      - back-end-config-check-job

