#Note: this may lack maturity
version: 2.1

commands:
  back-end-check-config-command:
    steps:
      - checkout
      - run: #Configuration check
          echo "Starting the configuration check."   && pwd

executors:
  back-end-executor:
    docker:
      # primary container
      # https://hub.docker.com/u/circleci/
      - image: circleci/openjdk

jobs:
  back-end-config-check-job:
    executor: back-end-executor
    steps:
      - back-end-check-config-command      

workflows:  
  back-end-config-check-workflow:
    jobs:
      - back-end-config-check-job

