# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  back-end-run-command:
    steps:
      - run: pwd 

executors:
  back-end-run-executor:
    docker:
      - image: cimg/openjdk:11.0

jobs: 
  back-end-run-job:     
    executor: back-end-run-executor
    steps: 
      - back-end-run-command    

workflows: 
  back-end-run-workflow: 
    jobs:
      - back-end-run-job
